project:
  title: "Rapportage waterkwaliteit 2025 - HHSK"
  type: book
  execute-dir: project
  # brand: "_extensions/HHSK-wkl/brand_hhsk/brand/_brand.yml"
  # post-render: 
  #  - "R/post_render_zwem_icons.R"

website: 
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Dit is nog een conceptversie!"
    type: warning
    position: above-navbar
  
book:
  title: "Rapportage waterkwaliteit 2025"
  navbar:
    search: true
    tools:
      - icon: github
        href: "https://github.com/HHSK-wkl/wklrap_2025"
    # background: "#D2EBEE"
    logo: logo-hhsk-wit
    pinned: false
  sidebar:
    title: "Rapportage waterkwaliteit 2025"
  page-footer: 
    center: 
      "![](images/schonevoeten.png){width=50%}"
  page-navigation: true
  twitter-card: true
  open-graph: true
  favicon: "_extensions/HHSK-wkl/brand_hhsk/brand/favicon.svg"
  # reader-mode: true
  # abstract-title: "Introductie"
  # abstract: ""
  # search: true
  date: today
  chapters:
    - "index.qmd"
    - part: "Het Ecosysteem"
      chapters: 
        - "01-zichtbare-toestand.qmd"
    - part: "Doelen en gebruik"
    - part: "Stoffen"
    # - "02-krw.qmd"
    # - "03-zwemwater.qmd"
    # - "04-nutrienten.qmd"
    # - "05-bestrijdingsmiddelen.qmd"
    # - "06-meetnetten.qmd"
    # - "09-meer_info.qmd"
    # - "98-colofon.qmd"

format:
  html:
    link-external-newwindow: true
    theme:
      - cosmo
      - brand
      - css/styles_wklrap.scss
    # fig-format: svg
    # cap-location: margin
    reference-location: document

lang: nl
language: 
  nl:
    section-title-abstract: ""
    title-block-published: "Datum"
    toc-title-document: "In dit hoofdstuk"
    crossref-fig-title: "Figuur"
    crossref-tbl-title: "Tabel"
    crossref-ch-prefix: "hoofdstuk"

fig-dpi: 150
knitr:
  opts_chunk:
    dev: "ragg_png"    

execute: 
  # freeze: auto
  echo: false
  warning: false
  message: false
